### ISSUE TITLE
Force close when choose Search By on Android 4.4

### ISSUE THREAD

**Issue by JustDragon** [plusCubed/matlog#28]
Hello,

I have been using Matlog for everyday and I love it very much. But since the update 1.1.1, I have force close issue when choose Search By on Android 4.4. Here is attached logcat of that. Hope you can fix it. Thank you very much!
[2017-06-18-13-44-41.txt](https://github.com/plusCubed/matlog/files/1150032/2017-06-18-13-44-41.txt)

**Comment by DVDAndroid** [comment]
Try this [apk](https://github.com/plusCubed/matlog/files/1168022/app-debug.zip), please

**Comment by JustDragon** [comment]
It works. Thank a lot!
