### ISSUE TITLE
Recording notification not working in 8.1

### ISSUE THREAD

**Issue by shuli81** [plusCubed/matlog#35]
As the title states, no notification when recording.
E: suppressing notification from package by user request.
E: No channel found for pkg=com.pluscubed.matlog...

**Comment by Unpublished** [comment]
Already fixed in https://github.com/plusCubed/matlog/commit/206bb16a256c578d8756afc1a9d1596ffa45186d

**Comment by plusCubed** [comment]
Should be rolling out with 1.2.0
