### ISSUE TITLE
Android 8.0 there always is a freeze

### ISSUE THREAD

**Issue by jidanni** [plusCubed/matlog#37]
On Android 8.0 there always is a freeze, with "Send Feedback?", and then after recovery if any, it needs help scrolling, with the user's finger. ASUS Zenfone 3. Matlog beta 1.1.1.

**Comment by jidanni** [comment]
So the project is unmaintained. Anybody have suggestions for an alternate?

**Comment by plusCubed** [comment]
Yes, I haven't had time to add anything new to the app, but I use it quite often on my Nexus 5 running 7.1 and Pixel running 8.1. Are you using root or adb permission granting?

**Comment by jidanni** [comment]
Yes I used adb to grant it the permissions.

**Comment by plusCubed** [comment]
Can you test with version 1.2.0 and see if this still occurs?

**Comment by jidanni** [comment]
OK seems better now.
