### ISSUE TITLE
Why does MatLog require network access ?

### ISSUE THREAD

**Issue by breversa** [plusCubed/matlog#39]
Why does MatLog require network access ?

[AFwall+](https://github.com/ukanth/afwall) reports that MatLog (v1.1.1 from IzzyOnDroid F-Droid repo : https://android.izzysoft.de/repo) tries to access `*.compute-1.amazonaws.com`

Why ?

**Comment by plusCubed** [comment]
The app reports crashes through Crashlytics. I'm working on releasing an F-Droid version with no network connectivity.

**Comment by breversa** [comment]
Thank you, that'd be great. :-)

**Comment by plusCubed** [comment]
F-Droid currently has the 1.1.2 release, with 1.2.0 coming soon.
