### ISSUE TITLE
Merge Omni fork

### ISSUE THREAD

**Issue by plusCubed** [plusCubed/matlog#40]
@maxwen @nathanchance @cooldroid @Unpublished  

I was completely unaware of this fork, and I'm flattered that MatLog would be included in OmniROM! I'll merge the improvements from the Omni fork if that is OK with you guys? I'm hoping to make a new release by the end of the month, on both Google Play and F-Droid.

https://github.com/omnirom/android_packages_apps_Matlog
https://github.com/cooldroid/matlog

**Comment by plusCubed** [comment]
I've started on this in the `omni` branch.

**Comment by Unpublished** [comment]
I would be in favor of splitting my changes to another PR/Branch as some of the commits are outdated (the refactor) or don't apply anymore because of your latest changes.
https://github.com/Unpublished/matlog/tree/dev_clean is rebased on current master.

**Comment by plusCubed** [comment]
@Unpublished It's somewhat difficult to pick apart the changes due to me preemptively resolving the merge conflicts... 😬

I'll make sure to do separate branch/PRs in the future, and keep these changes this time if that's OK with you? I think most of them still merge OK with the omni branch

**Comment by Unpublished** [comment]
I noticed that as well while I tried to rebase the omni branch. I'm OK with keeping it as is this time.

Will open a PR with the follow up changes then.

https://github.com/plusCubed/matlog/compare/omni#diff-c8cc2dd42271f2bf39c6aa81eb6a5529L8
I think we need to keep superuser permission outside of OmniROM, don't we?

**Comment by Unpublished** [comment]
Wasn't aware of that then I agree with removing it.

**Comment by plusCubed** [comment]
Merged. I need to do some more testing to make sure I didn't break anything.
