### ISSUE TITLE
Copy multiple logcat lines

### ISSUE THREAD

**Issue by orionlee** [plusCubed/matlog#49]
**Version:** v1.2.3

**Desired behavior:**
Users can only copy 1 log line at a time. It'd be great if users can select multiple lines and copy them.

**UI proposal:**
- when users long tap a log line, show additional option of "copy multiple line to clipboard"
- the line serves as the begin of the selection.
- when users tap another line, the lines between them will be copied.
  - The experience would be similar to the app's save partial feature, that let users select a subset of lines by marking beginning and end.

**Comment by SnowVolf** [comment]
This can be achived with [Menu -> File -> Save Partial]

**Comment by orionlee** [comment]
The motivation of this PR is for the cases that `[Menu -> File -> Save Partial]` is a bid too clunky, say, copying 5 lines from matlog to a message / note.

Another possibility could be that upon save partial is complete, it prompts users to optionally either open the partial log (in external editor) or share it, thus reducing the number of steps users need to take.
