### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by SecUpwN** [plusCubed/matlog#7]
Hi there @plusCubed, thanks for continuing and improving the awesome work of @nolanlawson! Would you please add your app to the FOSS store [F-Droid](https://f-droid.org/) so that privacy geeks like me get it without Google?

**Comment by plusCubed** [comment]
Sure, I'll look into it. I see the inclusion policy would involve removing some of the libraries I'm using (such as Fabric crash reporting), but it shouldn't be too difficult with build flavors.

**Comment by SecUpwN** [comment]
@plusCubed, why not change to the much more recommended [ACRA](v), which is also [on GitHub](https://github.com/ACRA/acra)?

**Comment by plusCubed** [comment]
@SecUpwN I used that before they turned off Google Forms support - now it's a bit more involved to use compared to Fabric. I'll probably just create a build flavor of matlog without Fabric.

**Comment by SecUpwN** [comment]
>I used that before they turned off Google Forms support

Good to know you already used `ACRA` and `Fabric`. Maybe you can add your experiences [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/659)?

**Comment by SecUpwN** [comment]
>I see the inclusion policy would involve removing some of the libraries I'm using (such as Fabric crash reporting)

We've ddecided to *not* use `ACRA`, but instead an advanced, more privacy-aware version of `Bugsnag`, maintained by @larsgrefer, one of our developers and aiming to be used by other apps as well. It is located at https://github.com/freefair/advanced-bugsnag-android. Hope this solves this Issue.

**Comment by Primokorn** [comment]
Any news on this? I have glitches now with Catlog so MatLog is more than welcome.

**Comment by collectorgeneral** [comment]
I just used it too, seems pretty good. Would be wonderful to have it on f-droid.

**Comment by pboesch** [comment]
hi, do you have an update about this? that is no updated app on fdroid to get android logs. Jour app seems to be great!

**Comment by swiftgeek** [comment]
@pboesch https://github.com/plusCubed/matlog/blob/master/app/build.gradle#L73 is the issue
Having it disabled for fdroid build would be probably the fastest way to get it into the repository

**Comment by revuwa** [comment]
@plusCubed: there is a f-droid packaging request now: https://gitlab.com/fdroid/rfp/issues/93 and as you expected before, Crashlytics (https://github.com/plusCubed/matlog/commit/ba0f9dab6f8dae5cfef6b25520e2e9deab3bff27) is the 	show-stopper for the moment.

Would you please consider to bring a build flavor of matlog without Crashlytics, or just removing it?

**Comment by c64bob** [comment]
Any news? I would love to have this app available in f-droid.

**Comment by Lionirdeadman** [comment]
Been 3 years since this issue was made... could you do it please, @plusCubed ?

**Comment by DamienCassou** [comment]
+1

**Comment by plusCubed** [comment]
Some progress/discussion: #23. I'm working on getting this completed.

**Comment by plusCubed** [comment]
Tracking at https://gitlab.com/fdroid/fdroiddata/merge_requests/3691.

**Comment by Grossdm** [comment]
Hello,
I hope this is a good place to ask my brief question.


Does the F-Droid version have any/all of three analytics removed?


Thanks for a great catlog GUI!


Doug®

**Comment by plusCubed** [comment]
There's only one analytics framework,  Firebase Crashlytics, and yes, it is removed in the F-Droid version.

**Comment by Grossdm** [comment]
Thank you!
I'm a bit confused about the F-Droid version, which I'm assuming is the same thing as "Matlog Libre" - is that part correct?

I did find Matlog on F-Droid, but I'm wondering if that version is available on GitHub or hosted on GitHub. There are references in the code in this repo to "fdroid" so perhaps that's why I'm befuddled by what I'm sure is a rather simple system.

Thank you for addressing my questions,

Doug

**Comment by plusCubed** [comment]
@Grossdm [MatLog Libre](https://f-droid.org/en/packages/com.pluscubed.matloglibre/) is the F-Droid version with analytics removed. It needs to be built by the F-Droid server with their signing key. I haven't bothered to download and re-upload it here (since it usually takes a while to build after the version tag is uploaded on GitHub). Hopefully that clarifies things! :)
