### ISSUE TITLE
Unable to view the log

### ISSUE THREAD

**Issue by Primokorn** [plusCubed/matlog#9]
Hi,
After recording a log through the widget, I can't view the log. The app is loading again and again.
Nexus 5 Android 6.0.1 - CM13 based rom - No issue with the good old Catlog.

Thanks for supporting this fork!

![unnamed](https://cloud.githubusercontent.com/assets/5938828/12882458/11d71f04-ce52-11e5-8854-35520eaf9506.png)

**Comment by aspiers** [comment]
I'm on a recent CM13.0 nightly (Android 6.0.1) and it works fine for me.

**Comment by aspiers** [comment]
BTW that's on a Galaxy S5.

**Comment by Primokorn** [comment]
I tried again (after launching the record through the widget or after opening the app) and I still have the same issue.

**Comment by DF1E** [comment]
On my first try unsing Matlog I used an AOSP rom with stock kernel and it didn't work. Now with a custom kernel (ElementalX) I tried this app again and it works now..

**Comment by Venereo** [comment]
From my experience I can tell it won't work with SElinux enabled. As soon as I disable it everything is OK. I'm in cm13 klte with boeffla kernel

**Comment by Venereo** [comment]
And I think is somehow related with supersu systemless root, I don't remember having the same problem with cm's internal root system

**Comment by Primokorn** [comment]
idk if this fork is still maintained but I noticed that force closing MatLog fixes this issues.
